---
image: docker:latest
services:
    - docker:dind

variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CI_CACHE_IMAGE_FILE: ella-ci-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID.tar
    DOCKER_DRIVER: overlay2
    BRANCH: $CI_COMMIT_REF_NAME
    PIPELINE_ID: ella-$CI_PIPELINE_ID

stages:
    - build
    - formatting
    - test
    - review
    - release

build:
    stage: build
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:ci-latest || true
        - docker build --cache-from $CI_REGISTRY_IMAGE:ci-latest -t $CI_REGISTRY_IMAGE:ci-latest -t $IMAGE_NAME -t ella:ci-latest --target dev .
        - docker push $CI_REGISTRY_IMAGE:ci-latest
        - mkdir -p images
        - docker save $IMAGE_NAME > images/$CI_CACHE_IMAGE_FILE
    tags:
        - do-small
    cache:
        key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
        paths:
            - images/
        policy: push

start_review:
    stage: review
    script:
        - make review REVIEW_NAME=${CI_BUILD_REF_SLUG}.review.ousamg.io
    environment:
        name: review/$CI_BUILD_REF_SLUG
        url: http://$CI_BUILD_REF_SLUG.review.ousamg.io
    only:
        - branches
    except:
        - master
    tags:
        - review
    needs: []

.test-common:
    stage: test
    before_script:
        - apk add --update make
        - cat images/$CI_CACHE_IMAGE_FILE | docker load
    needs: ['build']
    tags:
        - do-small
    cache:
        key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
        paths:
            - images/
        policy: pull

check_formatting:
    extends: .test-common
    stage: formatting
    script:
        - make test-formatting
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-formatting
    tags:
        - do-small

e2e:
    stage: test
    before_script:
        - apk add --update make
        - cat images/$CI_CACHE_IMAGE_FILE | docker load
        - rm -rf errorShots
    script: PARALLEL_INSTANCES=2 make test-e2e
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-e2e
    artifacts:
        paths:
            - errorShots/
            - logs/
        name: ella-e2e-errors-${CI_BUILD_REF_SLUG}
        when: on_failure
        expire_in: 2 weeks
    needs: ['build']
    tags:
        - do-small
    cache:
        key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
        paths:
            - images/
        policy: pull

api:
    extends: .test-common
    script:
        - make test-api
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-api
    tags:
        - do-small

api_migration:
    extends: .test-common
    script:
        - make test-api-migration
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-api-migration
    tags:
        - do-small

js:
    extends: .test-common
    script:
        - make test-js
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-js
    tags:
        - do-small

python:
    extends: .test-common
    script:
        - make test-python
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-common
    tags:
        - do-small

cli:
    extends: .test-common
    script:
        - make test-cli
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-cli
    tags:
        - do-small

report:
    extends: .test-common
    script:
        - make test-report
    after_script:
        - docker rm  -f -v ella-$CI_COMMIT_REF_NAME-report
    tags:
        - do-small

release:
    stage: release
    before_script:
        - apk add --update make git
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - RELEASE_TAG=$CI_COMMIT_REF_NAME make bundle-dist
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
    artifacts:
        paths:
            - ella-release-$CI_COMMIT_REF_NAME-dist.tgz
        name: ella-release-$CI_COMMIT_REF_NAME
        when: on_success
    only:
        - tags
    tags:
        - do-small
    needs: []
