---
image: docker:stable
services:
    - docker:stable-dind

variables:
    # build vars
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    BUILD_OPTIONS: --build-arg BUILDKIT_INLINE_CACHE=1

    # repo vars
    PIPELINE_ID: ella-$CI_PIPELINE_ID
    BRANCH: $CI_COMMIT_REF_NAME

    # image vars
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    REVAPP_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-review
    CI_CACHE_IMAGE_FILE: images/ella-ci-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID.tar
    SIF_RELEASE: ella-release-$CI_COMMIT_REF_NAME.sif

    # CI / release
    # Value is branch name when running on a branch pipeline, tag name for tag pipelines (releases)
    # RELEASE_TAG: $CI_COMMIT_REF_NAME
    # use docker:// when building singularity
    SIF_PREFIX: docker

    # ensure breakpoints don't fire accidentally
    PYTHONBREAKPOINT: 0
    # CI is all noninteractive
    DEBIAN_FRONTEND: noninteractive

    # singularity-in-docker
    SID_IMAGE: quay.io/singularity/singularity
    SID_VERSION: v3.7.1
    SID_SLUG: $SID_IMAGE:$SID_VERSION

    # from: https://gitlab.com/gitlab-org/cloud-deploy/-/releases/v0.3.3
    AWSCLI_IMAGE: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base@sha256:654cb6d3ba01f9753a4a3f20d6c39fb0b9c111d080bb6f90606cec284b4be7e9

stages: ['release-docker-src', 'release-singularity', 'release-upload']

# CI_DEBUG:
# - build
# - formatting
# - test
# - review
# - release-docker
# - release-artifacts

# shared settings
.cache: &cache
    key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
    paths:
        - images/
        - dist/

.cache-pull: &cache-pull
    <<: *cache
    policy: pull

.cache-push: &cache-push
    <<: *cache
    policy: push

.revapp-env: &revapp-env
    name: review/$CI_BUILD_REF_SLUG

# before_script actions
.apk-setup: &apk-setup apk update && apk add -u make git bash
.apt-setup: &apt-setup apt update && apt install --upgrade git make -y
.docker-login: &docker-login docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
.docker-load: &docker-load cat $CI_CACHE_IMAGE_FILE | docker load

# base jobs
.revapp: &revapp
    stage: review
    before_script:
        - *apk-setup
        - *docker-login
        - docker pull $REVAPP_IMAGE_NAME
    variables:
        REVAPP_REPLACE: 1
        REVAPP_NAME: $CI_BUILD_REF_SLUG
        REVAPP_COMMIT_SHA: $CI_COMMIT_SHA

.common-test: &common-test
    stage: test
    before_script:
        - *apk-setup
        - *docker-load
    needs: ['build']
    cache:
        <<: *cache-pull
    tags:
        - do-small
    except:
        - /^ops-.*$/

# jobs

.build: # CI_DEBUG
    stage: build
    before_script:
        - *apk-setup
        - *docker-login
    script:
        - docker pull $CI_REGISTRY_IMAGE:ci-latest || true
        - make build BUILD_OPTIONS="$BUILD_OPTIONS --cache-from $CI_REGISTRY_IMAGE:ci-latest -t $CI_REGISTRY_IMAGE:ci-latest"
        - docker push $CI_REGISTRY_IMAGE:ci-latest
        - make build-review
        - docker push $REVAPP_IMAGE_NAME
        - mkdir -p images
        - docker save $IMAGE_NAME > $CI_CACHE_IMAGE_FILE
    tags:
        - do-large
    cache:
        <<: *cache-push

.start_review: # CI_DEBUG
    extends: .revapp
    script:
        - make gitlab-review
    artifacts:
        reports:
            dotenv: deploy.env
    environment:
        <<: *revapp-env
        url: http://$APP_IP
        on_stop: stop_review
        auto_stop_in: 6 hours
    only:
        - branches
    except:
        - master

.stop_review: # CI_DEBUG
    extends: .revapp
    script:
        - make gitlab-review-stop
    when: manual
    environment:
        <<: *revapp-env
        action: stop

.refresh_ip: # CI_DEBUG
    extends: .revapp
    script:
        - make gitlab-review-refresh-ip
    artifacts:
        reports:
            dotenv: deploy.env
    environment:
        <<: *revapp-env
        url: http://$APP_IP
    when: manual

###

.check_formatting: # CI_DEBUG
    extends: .common-test
    stage: formatting
    script:
        - make test-formatting

.e2e: # CI_DEBUG
    extends: .common-test
    script:
        - PARALLEL_INSTANCES=2 make test-e2e
    artifacts:
        paths:
            - errorShots/
            - logs/
        name: ella-e2e-errors-${CI_BUILD_REF_SLUG}
        when: on_failure
        expire_in: 2 weeks
    cache:
        <<: *cache-pull

.api: # CI_DEBUG
    extends: .common-test
    script:
        - make test-api

.api_migration: # CI_DEBUG
    extends: .common-test
    script:
        - make test-api-migration

.js: # CI_DEBUG
    extends: .common-test
    script:
        - make test-js

.python: # CI_DEBUG
    extends: .common-test
    script:
        - make test-python

.cli: # CI_DEBUG
    extends: .common-test
    script:
        - make test-cli

.report: # CI_DEBUG
    extends: .common-test
    script:
        - make test-report

release_docker:
    stage: release-docker-src
    before_script:
        - *apk-setup
        - *docker-login
    script:
        - make ci-release-docker
    only:
        - branches # CI_DEBUG
        - tags
    tags:
        - do-large

release_src:
    stage: release-docker-src
    before_script:
        - *apk-setup
    script:
        - make ci-release-src
    artifacts:
        paths:
            - ella-release-*-dist.tgz
        when: on_success
    only:
        - branches # CI_DEBUG
        - tags
    tags:
        - do-small

release_singularity:
    image:
        name: $SID_SLUG
        entrypoint: ['']
    stage: release-singularity
    dependencies: ['release_docker']
    before_script:
        - *apk-setup
    script:
        - make ci-release-singularity
    artifacts:
        paths:
            - $SIF_RELEASE
        when: on_success
    only:
        - branches # CI_DEBUG
        - tags
    tags:
        - do-large

release_upload:
    stage: release-upload
    image: $AWSCLI_IMAGE
    before_script:
        - *apt-setup
    script:
        - make ci-release-upload
    dependencies: ['release_src', 'release_singularity']
    only:
        - branches # CI_DEBUG
        - tags
    tags:
        - do-large
