---
image: docker:stable
services:
    - docker:stable-dind

variables:
    GIT_SUBMODULE_STRATEGY: recursive

    # build vars
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: '1'
    BUILD_OPTIONS: --build-arg BUILDKIT_INLINE_CACHE=1

    # repo vars
    PIPELINE_ID: ella-$CI_PIPELINE_ID
    BRANCH: $CI_COMMIT_REF_NAME

    # image vars
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    REVAPP_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-review
    CI_CACHE_IMAGE_FILE: images/ella-ci-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID.tar

    # CI / release
    # Value is branch name when running on a branch pipeline, tag name for tag pipelines (releases)
    RELEASE_TAG: $CI_COMMIT_REF_NAME
    RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$RELEASE_TAG
    SIF_PREFIX: docker

    # singularity-in-docker
    SID_IMAGE: quay.io/singularity/singularity
    SID_VERSION: v3.8.1
    SID_SLUG: $SID_IMAGE:$SID_VERSION

    # from: https://gitlab.com/gitlab-org/cloud-deploy/-/releases/v0.3.3
    AWSCLI_IMAGE: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base@sha256:654cb6d3ba01f9753a4a3f20d6c39fb0b9c111d080bb6f90606cec284b4be7e9

    # Misc settings
    # ensure any breakpoints don't fire
    PYTHONBREAKPOINT: '0'
    DEBIAN_FRONTEND: noninteractive

    # Feature flags
    ENABLE_PYDANTIC: 'true'

default:
    # allow running jobs to be canceled if a new pipeline starts before they finish
    # ref: https://docs.gitlab.com/ee/ci/yaml/index.html#interruptible
    interruptible: true

stages:
    - build
    - formatting
    - test
    - review
    - release-docker
    - release-singularity-src
    - release-upload

# shared settings
.cache: &cache
    key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
    paths:
        - images/
    policy: pull-push

.cache-pull: &cache-pull
    <<: *cache
    policy: pull

.cache-push: &cache-push
    <<: *cache
    policy: push

.revapp-env: &revapp-env
    name: review/$CI_BUILD_REF_SLUG

# before_script actions
.apk-setup: &apk-setup apk update && apk add -u make git bash
.apt-setup: &apt-setup apt-get update -qq && apt-get install -qq --no-install-recommends git make
.docker-login: &docker-login docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
# pull the last registry image if the cache has expired
.docker-load: &docker-load cat $CI_CACHE_IMAGE_FILE | docker load || docker pull $IMAGE_NAME

# base jobs
.revapp:
    stage: review
    before_script:
        - *apk-setup
        - *docker-login
    variables:
        REVAPP_REPLACE: 1
        REVAPP_NAME: $CI_BUILD_REF_SLUG
        REVAPP_COMMIT_SHA: $CI_COMMIT_SHA

.common-test:
    stage: test
    before_script:
        - *apk-setup
        - *docker-load
        - make ci-set-testdata
    needs: ['build']
    artifacts:
        paths:
            - logs/
        name: ella-${CI_JOB_NAME}-errors-${CI_BUILD_REF_SLUG}
        when: on_failure
        expire_in: 2 weeks
    cache:
        <<: *cache-pull
    tags:
        - do-small
    except:
        - /^ops-.*$/

# jobs

build:
    stage: build
    before_script:
        - *apk-setup
        - *docker-login
    script:
        - make ci-build-dev
    tags:
        - do-large
    cache:
        <<: *cache-push

build_review:
    extends: .revapp
    script:
        - make ci-build-review

# review env failing should not block a merge
start_review:
    extends: .revapp
    needs: ['build_review']
    script:
        - make gitlab-review
    artifacts:
        reports:
            dotenv: deploy.env
    environment:
        <<: *revapp-env
        url: http://$APP_IP
        on_stop: stop_review
        auto_stop_in: 6 hours
    allow_failure: true
    only:
        - branches
    except:
        refs:
            - master
        variables:
            - $CI_COMMIT_MESSAGE =~ /\bskip-review\b/

stop_review:
    extends: .revapp
    script:
        - make gitlab-review-stop
    when: manual
    environment:
        <<: *revapp-env
        action: stop

refresh_ip:
    extends: .revapp
    script:
        - make gitlab-review-refresh-ip
    artifacts:
        reports:
            dotenv: deploy.env
    environment:
        <<: *revapp-env
        url: http://$APP_IP
    when: manual

###

check_formatting:
    extends: .common-test
    stage: formatting
    script:
        - make test-formatting
    except:
        variables:
            - $UPSTREAM_TRIGGER

check_testdata:
    extends: .common-test
    script:
        - make test-testdata

e2e:
    extends: .common-test
    script:
        - make test-e2e
    artifacts:
        paths:
            - errorShots/
            - logs/
        name: ella-e2e-errors-${CI_BUILD_REF_SLUG}
        when: on_failure
        expire_in: 2 weeks

api:
    extends: .common-test
    script:
        - make test-api

api_migration:
    extends: .common-test
    script:
        - make test-api-migration

js:
    extends: .common-test
    script:
        - make test-js

python:
    extends: .common-test
    script:
        - make test-python

cli:
    extends: .common-test
    script:
        - make test-cli

report:
    extends: .common-test
    script:
        - make test-report

dump_schemas:
    extends: .common-test
    needs: ['e2e', 'api', 'python']
    script:
        - make dump-schemas
    artifacts:
        paths:
            - schemas_${CI_COMMIT_REF_NAME}.json
            - schemas_${CI_COMMIT_REF_NAME}.ts

release_docker:
    stage: release-docker
    before_script:
        - *apk-setup
        - *docker-login
    script:
        - make ci-release-docker
    only:
        - tags
    tags:
        - do-large

release_src:
    stage: release-singularity-src
    before_script:
        - *apk-setup
    script:
        - make ci-release-src
    only:
        - tags
    artifacts:
        paths:
            - dist/ella-release-*-dist.tgz
        name: src-$CI_COMMIT_REF_NAME
        expire_in: 1 week
    tags:
        - do-small

release_singularity:
    image:
        name: $SID_SLUG
        entrypoint: ['']
    stage: release-singularity-src
    dependencies: ['release_docker']
    before_script:
        - *apk-setup
    script:
        - make ci-release-singularity
    only:
        - tags
    artifacts:
        paths:
            - '**/*.sif'
        name: singularity-$CI_COMMIT_REF_NAME
        expire_in: 1 week
    tags:
        - do-large

release_upload:
    stage: release-upload
    image: $AWSCLI_IMAGE
    dependencies: ['release_src', 'release_singularity']
    before_script:
        - *apt-setup
    script:
        - make ci-release-upload
    only:
        - tags
    tags:
        - do-large
