version: "3.3"

networks:
  ella-network:
    name: ella-network

services:
  dbreset:
    image: legacy
    container_name: dbreset
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    entrypoint: python /ella/ops/testdata/reset-testdata.py
    volumes:
      - .:/ella
    networks:
      - ella-network
    environment:
      - DB_URL=$DB_URL
      - DEVELOP=true
    depends_on:
      postgres:
        condition: service_healthy
  backendv1:
    image: legacy
    container_name: backendv1
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - .:/ella
    networks:
      - ella-network
    environment:
      - DB_URL=$DB_URL
      - DEVELOP=true
    depends_on:
      dbreset:
        condition: service_completed_successfully
  webpack_legacy:
    image: legacy
    container_name: webpack_legacy
    volumes:
      - .:/ella
    working_dir: /ella/src/webui
    command: yarn dev
    networks:
      - ella-network
    ports:
      - "35729:35729"
    depends_on:
      - backendv1
      - postgres
      - nginx
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    networks:
      - ella-network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-h",
          "localhost"
        ]
      interval: 1s
      timeout: 2s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  nginx:
    image: nginx
    container_name: ella-nginx
    ports:
      - "8080:8080"
    entrypoint:
      - /etc/nginx/common_nginx_startup
    volumes:
      - ./ops/common/nginx.tmpl.conf:/etc/nginx/nginx.tmpl.conf
      - ./ops/common/common_nginx_startup:/etc/nginx/common_nginx_startup
      - ${LOGS}:/logs
      - ./src/webui/build:/static
    networks:
      - ella-network
    environment:
      PORT: 8080
    depends_on:
      - backendv1
      - postgres
