# coding=utf-8
rules = [
    #### JSON rules (copy/paste entire column between [] in "rules = []", remove last ",")
    ### GP_REQ
    { "code": "REQ_GP_inh_ad", "rule": {"genepanel.gp_inheritance": "autosomal_dominant"}},
    { "code": "REQ_GP_inh_ar", "rule": {"genepanel.gp_inheritance": "autosomal_recessive"}},
    { "code": "REQ_GP_inh_xd", "rule": {"genepanel.gp_inheritance": "x-linked_dominant"}},
    { "code": "REQ_GP_inh_xr", "rule": {"genepanel.gp_inheritance": "x-linked_recessive"}},
    { "code": "REQ_GP_last_exon_important", "rule": {"genepanel.gp_last_exon": "last_exon_important"}},
    { "code": "REQ_GP_last_exon_not_important", "rule": {"genepanel.gp_last_exon": "last_exon_not_important"}},
    { "code": "REQ_GP_lof_missense", "rule": {"genepanel.gp_disease_mode": "lof_missense"}},
    { "code": "REQ_GP_lof_only", "rule": {"genepanel.gp_disease_mode": "lof_only"}},
    { "code": "REQ_GP_missense_only", "rule": {"genepanel.gp_disease_mode": "missense_only"}},
    ### REQ
    { "code": "REQ_>=4affected", "rule": {"refassessment.*.ref_population": "in_many_aff"}},
    { "code": "REQ_2affected", "rule": {"refassessment.*.ref_population": "in_few_aff"}},
    { "code": "REQ_3affected", "rule": {"refassessment.*.ref_population": "in_more_aff"}},
    { "code": "REQ_aa_diff", "rule": {"refassessment.*.ref_aa_overlap_sim": "diff_prop"}},
    { "code": "REQ_aa_sim", "rule": {"refassessment.*.ref_aa_overlap_sim": "sim_prop"}},
    { "code": "REQ_abnormal_protein", "rule": {"refassessment.*.ref_prot": "prot_abnormal"}},
    { "code": "REQ_abnormal_RNA", "rule": {"refassessment.*.ref_rna": "rna_abnormal"}},
    { "code": "REQ_crit_domain", "rule": {"refassessment.*.ref_domain_overlap": "crit_domain"}},
    { "code": "REQ_crit_domain", "rule": {"prediction.Domain": "crit_domain"}},
    { "code": "REQ_hi_freq", "rule": {"frequencies.cutoff.ExAC": ">=hi_freq_cutoff"}},
    { "code": "REQ_hi_freq", "rule": {"frequencies.cutoff.1000G": ">=hi_freq_cutoff"}},
    { "code": "REQ_hi_freq", "rule": {"frequencies.cutoff.ESP6500": ">=hi_freq_cutoff"}},
    { "code": "REQ_hi_freq", "rule": {"frequencies.cutoff.inDB": ">=hi_freq_cutoff"}},
    { "code": "REQ_IHC_HQ", "rule": {"refassessment.*.ref_ihc_quality": "ihc_HQ"}},
    { "code": "REQ_IHC_MQ", "rule": {"refassessment.*.ref_ihc_quality": "ihc_MQ"}},
    { "code": "REQ_in_autozygous", "rule": {"genomic.autozygosity": "in_autozygous"}},
    { "code": "REQ_in_last_exon", "rule": {"transcript.in_last_exon": "yes"}},
    { "code": "REQ_in_trans_pathogenic", "rule": {"genomic.phase": "in_trans_pathogenic"}},
    { "code": "REQ_inframe", "rule": {"transcript.Consequence": {"$in": ["inframe_insertion", "inframe_deletion"]}}},
    { "code": "REQ_less_common", "rule": {"frequencies.cutoff.ExAC": {"$all": [">=lo_freq_cutoff", "<hi_freq_cutoff"]}}},
    { "code": "REQ_less_common", "rule": {"frequencies.cutoff.1000G": {"$all": [">=lo_freq_cutoff", "<hi_freq_cutoff"]}}},
    { "code": "REQ_less_common", "rule": {"frequencies.cutoff.ESP6500": {"$all": [">=lo_freq_cutoff", "<hi_freq_cutoff"]}}},
    { "code": "REQ_less_common", "rule": {"frequencies.cutoff.inDB": {"$all": [">=lo_freq_cutoff", "<hi_freq_cutoff"]}}},
    { "code": "REQ_missense", "rule": {"transcript.Consequence": {"$in": ["missense_variant", "protein_altering_variant"]}}},
    { "code": "REQ_MMR_loss", "rule": {"refassessment.*.ref_ihc": "mmr_loss"}},
    { "code": "REQ_MSI", "rule": {"refassessment.*.ref_msi": "msi"}},
    { "code": "REQ_MSI_HQ", "rule": {"refassessment.*.ref_msi_quality": "msi_HQ"}},
    { "code": "REQ_MSI_MQ", "rule": {"refassessment.*.ref_msi_quality": "msi_MQ"}},
    { "code": "REQ_no_aa_change", "rule": {"transcript.Consequence": {"$in": ["stop_retained_variant", "5_prime_UTR_variant", "3_prime_UTR_variant", "non_coding_transcript_exon_variant", "non_coding_transcript_variant", "intron_variant", "upstream_gene_variant", "downstream_gene_variant", "intergenic_variant", "synonymous_variant"]}}},
    { "code": "REQ_no_MSI", "rule": {"refassessment.*.ref_msi": "no_msi"}},
    { "code": "REQ_no_segregation", "rule": {"refassessment.*.ref_segregation": "no_segr"}},
    # Manual edit
    { "code": "REQ_no_splice_effect", "rule": {"transcript.splice_Effect": {"$or": [{"$in": ["predicted_conserved", "consensus_not_affected", "not_transcribed"]}, {"$not": {"$in": ["de_novo"]}}]}}},
    { "code": "REQ_normal_protein", "rule": {"refassessment.*.ref_prot": "prot_normal"}},
    { "code": "REQ_normal_RNA", "rule": {"refassessment.*.ref_rna": "rna_normal"}},
    { "code": "REQ_not_in_last_exon", "rule": {"transcript.in_last_exon": "no"}},
    { "code": "REQ_novel_aa", "rule": {"refassessment.*.ref_aa_overlap_same_novel": "novel_aa"}},
    { "code": "REQ_null", "rule": {"transcript.Consequence": {"$in": ["start_lost", "initiator_codon_variant", "transcript_ablation", "splice_donor_variant", "splice_acceptor_variant", "stop_gained", "frameshift_variant"]}}},
    { "code": "REQ_null_freq", "rule": {"frequencies.cutoff.ExAC": "null_freq"}},
    { "code": "REQ_null_freq", "rule": {"frequencies.cutoff.1000G": "null_freq"}},
    { "code": "REQ_null_freq", "rule": {"frequencies.cutoff.ESP6500": "null_freq"}},
    { "code": "REQ_null_freq", "rule": {"frequencies.cutoff.inDB": "null_freq"}},
    { "code": "REQ_overlap_ben", "rule": {"refassessment.*.ref_aa_overlap": "overlap_ben"}},
    { "code": "REQ_overlap_HQ", "rule": {"refassessment.*.ref_aa_overlap_quality": "overlap_HQ"}},
    { "code": "REQ_overlap_MQ", "rule": {"refassessment.*.ref_aa_overlap_quality": "overlap_MQ"}},
    { "code": "REQ_overlap_pat", "rule": {"refassessment.*.ref_aa_overlap": "overlap_pat"}},
    { "code": "REQ_protein_HQ", "rule": {"refassessment.*.ref_prot_quality": "prot_HQ"}},
    { "code": "REQ_protein_MQ", "rule": {"refassessment.*.ref_prot_quality": "prot_MQ"}},
    { "code": "REQ_repeat", "rule": {"refassessment.*.ref_repeat_overlap": "repeat"}},
    { "code": "REQ_repeat", "rule": {"genomic.Domain": "repeat"}},
    { "code": "REQ_RNA_HQ", "rule": {"refassessment.*.ref_rna_quality": "rna_HQ"}},
    { "code": "REQ_RNA_MQ", "rule": {"refassessment.*.ref_rna_quality": "rna_MQ"}},
    { "code": "REQ_same_aa", "rule": {"refassessment.*.ref_aa_overlap_same_novel": "same_aa"}},
    { "code": "REQ_segregation", "rule": {"refassessment.*.ref_segregation": "segr"}},
    { "code": "REQ_segregation_HQ", "rule": {"refassessment.*.ref_segregation_quality": "segr_HQ"}},
    { "code": "REQ_segregation_MQ", "rule": {"refassessment.*.ref_segregation_quality": "segr_MQ"}},
    { "code": "REQ_segregation_WQ", "rule": {"refassessment.*.ref_segregation_quality": "segr_WQ"}},
    ### PVS*
    # Manual edit
    { "code": "PVS1","rule": {"$$aggregate": {"$and":["REQ_null",{"$in": ["REQ_GP_lof_missense", "REQ_GP_lof_only"]},{"$or": ["REQ_not_in_last_exon",{"$all": ["REQ_in_last_exon","REQ_GP_last_exon_important"]}]}]}}},
    ### PS*
    { "code": "PS1", "rule": {"$$aggregate": {"$all": ["REQ_overlap_pat", "REQ_same_aa", "REQ_overlap_HQ"]}}},
    { "code": "PS2", "rule": {"family.de_novo": "de_novo_confirmed"}},
    { "code": "PS3", "rule": {"$$aggregate": {"$all": ["REQ_abnormal_protein", "REQ_prot_HQ"]}}},
    { "code": "PS3", "rule": {"$$aggregate": {"$all": ["REQ_abnormal_RNA", "REQ_RNA_HQ"]}}},
    { "code": "PS3", "rule": {"$$aggregate": {"$all": ["REQ_MSI", "REQ_MSI_HQ"]}}},
    { "code": "PS3", "rule": {"$$aggregate": {"$all": ["REQ_MMR_loss", "REQ_IHC_HQ"]}}},
    { "code": "PS4", "rule": {"$$aggregate": {"$all": ["REQ_>=4affected", "REQ_null_freq"]}}},
    { "code": "PSxPM1", "rule": {"refassessment.*.ref_crit_site": "crit_site"}},
    { "code": "PSxPM1", "rule": {"prediction.Domain": "crit_site"}},
    { "code": "PSxPP1", "rule": {"refassessment.*.ref_segregation": {"$all": ["REQ_segregation", "REQ_segregation_HQ"]}}},
    { "code": "PSxPP1", "rule": {"family.segregation": {"$all": ["REQ_segregation", "REQ_segregation_HQ"]}}},
    ### PM*
    { "code": "PM1", "rule": {"$$aggregate": ["REQ_crit_domain", {"$not": {"$in": ["PSxPM1"]}}]}},
    { "code": "PM1", "rule": {"refassessment.*.ref_mut_hotspot": "mut_hotspot"}},
    # PM2 (not implemented)
    { "code": "PM3", "rule": {"$$aggregate": {"$all": ["REQ_in_trans_pathogenic", "REQ_GP_inh_ar"]}}},
    { "code": "PM4", "rule": {"transcript.Consequence": "stop_lost"}},
    # Manual edit
    { "code": "PM4", "rule": {"$$aggregate": {"$and": ["REQ_inframe", {"$not": {"$in": ["REQ_repeat"]}}]}}},
    { "code": "PM5", "rule": {"$$aggregate": {"$all": ["REQ_overlap_pat", "REQ_novel_aa", "REQ_aa_sim", "REQ_overlap_HQ"]}}},
    { "code": "PM6", "rule": {"family.de_novo": "de_novo_unconfirmed"}},
    { "code": "PMxN1", "rule": {"$$aggregate": {"$all": ["REQ_in_autozygous", "REQ_GP_inh_ar"]}}},
    { "code": "PMxPP1", "rule": {"refassessment.*.ref_segregation": {"$all": ["REQ_segregation", "REQ_segregation_MQ"]}}},
    { "code": "PMxPP1", "rule": {"family.segregation": {"$all": ["REQ_segregation", "REQ_segregation_MQ"]}}},
    { "code": "PMxPS1", "rule": {"$$aggregate": {"$all": ["REQ_overlap_pat", "REQ_same_aa", "REQ_overlap_MQ"]}}},
    { "code": "PMxPS3", "rule": {"$$aggregate": {"$all": ["REQ_abnormal_protein", "REQ_prot_MQ"]}}},
    { "code": "PMxPS3", "rule": {"$$aggregate": {"$all": ["REQ_abnormal_RNA", "REQ_RNA_MQ"]}}},
    { "code": "PMxPS3", "rule": {"$$aggregate": {"$all": ["REQ_MSI", "REQ_MSI_MQ"]}}},
    { "code": "PMxPS3", "rule": {"$$aggregate": {"$all": ["REQ_MMR_loss", "REQ_IHC_MQ"]}}},
    { "code": "PMxPS4", "rule": {"$$aggregate": {"$all": ["REQ_3affected", "REQ_null_freq"]}}},
    ### PP*
    { "code": "PP1", "rule": {"refassessment.*.ref_segregation": {"$all": ["REQ_segregation", "REQ_segregation_WQ"]}}},
    { "code": "PP1", "rule": {"family.segregation": {"$all": ["REQ_segregation", "REQ_segregation_WQ"]}}},
    # Manual edit
    { "code": "PP2","rule": {"$$aggregate": {"$and":["REQ_missense",{"$in": ["REQ_GP_lof_missense","REQ_GP_missense_only"]}]}}},
    { "code": "PP3", "rule": {"transcript.splice_Effect": {"$in": ["predicted_lost ", "de_novo"]}}},
    { "code": "PP3", "rule": {"prediction.Conservation": "conserved"}},
    { "code": "PP3", "rule": {"external.IARC-BRCA": {"$in": ["4", "5"]}}},
    # PP4 (not implemented)
    { "code": "PP5", "rule": {"external.[Trusted source]": "Pathogenic"}},
    # Manual edit
    { "code": "PPxPM2", "rule": {"$$aggregate": {"$and": ["REQ_null_freq", {"$not": {"$in": ["REQ_less_common","REQ_hi_freq"]}}]}}},
    { "code": "PPxPM5", "rule": {"$$aggregate": {"$or": [{"$all": ["REQ_overlap_pat", "REQ_novel_aa", "REQ_aa_sim", "REQ_overlap_MQ"]}, {"$all": ["REQ_overlap_pat", "REQ_novel_aa", "REQ_aa_diff", "REQ_overlap_HQ"]}]}}},
    { "code": "PPxPS4", "rule": {"$$aggregate": {"$all": ["REQ_2affected", "REQ_null_freq"]}}},
    ### BP*
    { "code": "BP1", "rule": {"$$aggregate": {"$all": ["REQ_missense", "REQ_GP_lof_only"]}}},
    { "code": "BP2", "rule": {"family.phase": "in_cis_pathogenic"}},
    { "code": "BP2", "rule": {"$$aggregate": {"$all": ["REQ_in_trans_pathogenic", "REQ_GP_inh_ad"]}}},
    { "code": "BP3", "rule": {"$$aggregate": {"$all": ["REQ_inframe", "REQ_repeat"]}}},
    # Manual edit
    { "code": "BP4", "rule": {"transcript.splice_Effect": {"$or": [{"$in": ["predicted_conserved", "consensus_not_affected", "not_transcribed"]}, {"$not": {"$in": ["de_novo"]}}]}}},
    { "code": "BP4", "rule": {"prediction.Conservation": "non-conserved"}},
    # BP5 (not implemented)
    { "code": "BP6", "rule": {"external.[Trusted source]": "Benign"}},
    { "code": "BPxBS3", "rule": {"$$aggregate": {"$all": ["REQ_normal_protein", "REQ_prot_MQ"]}}},
    { "code": "BPxBS3", "rule": {"$$aggregate": {"$all": ["REQ_normal_RNA", "REQ_RNA_MQ"]}}},
    { "code": "BPxBS3", "rule": {"$$aggregate": {"$all": ["REQ_no_MSI", "REQ_MSI_MQ"]}}},
    { "code": "BPxBS4", "rule": {"refassessment.*.ref_segregation": {"$all": ["REQ_no_segregation", "REQ_segregation_MQ"]}}},
    { "code": "BPxBS4", "rule": {"family.segregation": {"$all": ["REQ_no_segregation", "REQ_segregation_MQ"]}}},
    { "code": "BPxPM5", "rule": {"$$aggregate": {"$all": ["REQ_overlap_ben", "REQ_same_aa", "REQ_overlap_HQ"]}}},
    ### BS*
    { "code": "BS1", "rule": {"$$aggregate": {"$all": ["REQ_less_common", "REQ_GP_inh_ad"]}}},
    { "code": "BS2", "rule": {"refassessment.*.ref_population": "in_healthy"}},
    { "code": "BS3", "rule": {"$$aggregate": {"$all": ["REQ_normal_protein", "REQ_prot_HQ"]}}},
    { "code": "BS3", "rule": {"$$aggregate": {"$all": ["REQ_normal_RNA", "REQ_RNA_HQ"]}}},
    { "code": "BS3", "rule": {"$$aggregate": {"$all": ["REQ_no_MSI", "REQ_MSI_HQ"]}}},
    { "code": "BS3", "rule": {"$$aggregate": {"$all": ["REQ_MMR_loss", "REQ_IHC_HQ"]}}},
    { "code": "BS4", "rule": {"refassessment.*.ref_segregation": {"$all": ["REQ_no_segregation", "REQ_segregation_HQ"]}}},
    { "code": "BS4", "rule": {"family.segregation": {"$all": ["REQ_no_segregation", "REQ_segregation_HQ"]}}},
    { "code": "BSxBP4", "rule": {"external.IARC-BRCA": {"$in": ["1", "2"]}}},
    { "code": "BSxBP7", "rule": {"$$aggregate": {"$all": ["REQ_no_aa_change", "REQ_no_splice_effect"]}}},
    ### BA*
    { "code": "BA1", "rule": {"frequencies.cutoff.ExAC": ">=hi_freq_cutoff"}},
    { "code": "BA1", "rule": {"frequencies.cutoff.1000G": ">=hi_freq_cutoff"}},
    { "code": "BA1", "rule": {"frequencies.cutoff.ESP6500": ">=hi_freq_cutoff"}},
    { "code": "BA1", "rule": {"frequencies.cutoff.inDB": ">=hi_freq_cutoff"}},



#    {
#        "code": "XXX",
#        "rule": {"$$aggregate": {"$atleast": [1, "REQ-1", "REQ-2", "REQ-3"]}}
#    },

]
