# coding=utf-8
rules = [
    #### JSON (copy/paste entire column between [] in "rules = []", remove last ",")
    ### GP_REQ
    { "code": "REQ_GP_inh_ad", "rule": {"genepanel.gp_inheritance": "autosomal_dominant"}},
    { "code": "REQ_GP_inh_ar", "rule": {"genepanel.gp_inheritance": "autosomal_recessive"}},
    { "code": "REQ_GP_inh_xd", "rule": {"genepanel.gp_inheritance": "x-linked_dominant"}},
    { "code": "REQ_GP_inh_xr", "rule": {"genepanel.gp_inheritance": "x-linked_recessive"}},
    { "code": "REQ_GP_last_exon_important", "rule": {"genepanel.gp_last_exon": "last_exon_important"}},
    { "code": "REQ_GP_last_exon_not_important", "rule": {"genepanel.gp_last_exon": "last_exon_not_important"}},
    { "code": "REQ_GP_lof_missense", "rule": {"genepanel.gp_disease_mode": "lof_missense"}},
    { "code": "REQ_GP_lof_only", "rule": {"genepanel.gp_disease_mode": "lof_only"}},
    { "code": "REQ_GP_missense_only", "rule": {"genepanel.gp_disease_mode": "missense_only"}},
    ### REQ
    { "code": "REQ_in_autozygous", "rule": {"genomic.autozygosity": "in_autozygous"}},
    { "code": "REQ_in_last_exon", "rule": {"transcript.domain": "in_last_exon"}},
    { "code": "REQ_in_trans_pathogenic", "rule": {"genomic.phase": "in_trans_pathogenic"}},
    { "code": "REQ_inframe", "rule": {"transcript.Consequence": {"$in": ["inframe_insertion", "inframe_deletion"]}}},
    { "code": "REQ_missense", "rule": {"transcript.Consequence": "missense_variant"}},
    { "code": "REQ_no_aa_change", "rule": {"transcript.Consequence": {"$in": ["stop_retained_variant", "5_prime_UTR_variant", "3_prime_UTR_variant", "non_coding_exon_variant", "nc_transcript_variant", "intron_variant", "upstream_gene_variant", "downstream_gene_variant", "intergenic_variant", "synonymous_variant"]}}},
    { "code": "REQ_no_splice_effect", "rule": {"transcript.splice_Effect": "no_effect"}},
    { "code": "REQ_non-conserved", "rule": {"genomic.conservation": "non-conserved"}},
    { "code": "REQ_non-repeat", "rule": {"transcript.domain": "non-repeat"}},
    { "code": "REQ_not_in_last_exon", "rule": {"transcript.domain": "not_in_last_exon"}},
    { "code": "REQ_rare", "rule": {"frequencies.ExAC_1000G_ESP6500": "<lo_freq_cutoff"}},
    { "code": "REQ_rare_match", "rule": {"frequencies.inDB": "<lo_freq_cutoff"}},
    { "code": "REQ_overlap_pat", "rule": {"refassessment.*.ref_aa_overlap": "overlap_pat"}},
    { "code": "REQ_overlap_ben", "rule": {"refassessment.*.ref_aa_overlap": "overlap_ben"}},
    { "code": "REQ_same_aa", "rule": {"refassessment.*.ref_aa_overlap_same_novel": "same_aa"}},
    { "code": "REQ_novel_aa", "rule": {"refassessment.*.ref_aa_overlap_same_novel": "novel_aa"}},
    { "code": "REQ_aa_sim", "rule": {"refassessment.*.ref_aa_overlap_sim": "sim_prop"}},
    { "code": "REQ_aa_diff", "rule": {"refassessment.*.ref_aa_overlap_sim": "diff_prop"}},
    { "code": "REQ_repeat", "rule": {"refassessment.*.ref_repeat_overlap": "repeat"}},
    { "code": "REQ_repeat", "rule": {"genomic.domain": "repeat"}},
    { "code": "REQ_null", "rule": {"transcript.Consequence": {"$in": ["transcript_ablation", "splice_donor_variant", "splice_acceptor_variant", "stop_gained", "frameshift_variant"]}}},
    ### PVS*
    # Manual edit
    { "code": "PVS1","rule": {"$$aggregate": {"$and":["REQ_null",{"$in": ["REQ_GP_lof_missense", "REQ_GP_lof_only"]},{"$or": ["REQ_not_in_last_exon",{"$all": ["REQ_in_last_exon","REQ_GP_last_exon_important"]}]}]}}},
    { "code": "PVSX1", "rule": {"external.BIC.Clinically_Important": "yes"}},
    ### PS*
    { "code": "PS1", "rule": {"$$aggregate": {"$all": ["REQ_overlap_pat", "REQ_same_aa"]}}},
    { "code": "PS2", "rule": {"family.de_novo": "de_novo_confirmed"}},
    { "code": "PS3", "rule": {"refassessment.*.ref_prot": "prot++"}},
    { "code": "PS3", "rule": {"refassessment.*.ref_rna": "rna++"}},
    { "code": "PS3", "rule": {"refassessment.*.ref_msi": "msi++"}},
    { "code": "PS3", "rule": {"refassessment.*.ref_ihc": "mmr_loss++"}},
    { "code": "PS4", "rule": {"refassessment.*.ref_population": "rr_5"}},
    { "code": "PSX1", "rule": {"transcript.InSight": {"$in": ["Path: +/?", "Path: +/+"]}}},
    { "code": "PSX2", "rule": {"refassessment.*.ref_segregation": "segr+++"}},
    { "code": "PSX2", "rule": {"family.segregation": "segr+++"}},
    ### PM*
    { "code": "PM1", "rule": {"refassessment.*.ref_domain_overlap": "crit_domain"}},
    { "code": "PM1", "rule": {"transcript.domain": "crit_domain"}},
    { "code": "PM2", "rule": {"frequencies.inDB": "null_freq"}},
    { "code": "PM2", "rule": {"$$aggregate": {"$all": ["REQ_rare_match", "REQ_GP_inh_ar"]}}},
    { "code": "PM3", "rule": {"$$aggregate": {"$all": ["REQ_in_trans_pathogenic", "REQ_GP_inh_ar"]}}},
    { "code": "PM4", "rule": {"transcript.Consequence": {"$in": ["transcript_amplification", "stop_lost"]}}},
    { "code": "PM4", "rule": {"$$aggregate": {"$all": ["REQ_inframe", "REQ_non-repeat"]}}},
    { "code": "PM5", "rule": {"$$aggregate": {"$all": ["REQ_overlap_pat", "REQ_novel_aa", "REQ_aa_sim"]}}},
    { "code": "PM6", "rule": {"family.de_novo": "de_novo_unconfirmed"}},
    { "code": "PMX1", "rule": {"refassessment.*.ref_prot": "prot+"}},
    { "code": "PMX1", "rule": {"refassessment.*.ref_rna": "rna+"}},
    { "code": "PMX1", "rule": {"refassessment.*.ref_msi": "msi+"}},
    { "code": "PMX1", "rule": {"refassessment.*.ref_mmr": "mmr_loss+"}},
    { "code": "PMX2", "rule": {"refassessment.*.ref_segregation": "segr++"}},
    { "code": "PMX2", "rule": {"family.segregation": "segr++"}},
    { "code": "PMX3", "rule": {"refassessment.*.ref_population": "in_affecteds"}},
    { "code": "PMX4", "rule": {"$$aggregate": {"$all": ["REQ_in_autozygous", "REQ_GP_inh_ar"]}}},
    ### PP*
    { "code": "PP1", "rule": {"refassessment.*.ref_segregation": "segr+"}},
    { "code": "PP1", "rule": {"family.segregation": "segr+"}},
    { "code": "PP2", "rule": {"transcript.Consequence": {"$in": ["splice_region_variant", "initiator_codon_variant"]}}},
    # Manual edit
    # This rule *must* be placed after rules for PS1 and PM5
    { "code": "PP2","rule": {"$$aggregate": {"$and":["REQ_missense",{"$in": ["REQ_GP_lof_missense","REQ_GP_missense_only"]},{"$not": {"$in": ["PS1","PM5"]}}]}}},
    { "code": "PP3", "rule": {"refassessment.*.ref_prediction": "pat"}},
    { "code": "PP3", "rule": {"transcript.SIFT": "deleterious"}},
    { "code": "PP3", "rule": {"transcript.PP2": "probably_damaging"}},
    { "code": "PP3", "rule": {"transcript.splice_Effect": {"$in": ["lost_site", "de_novo"]}}},
    { "code": "PP3", "rule": {"transcript.CADD": "[in top 1%]"}},
    { "code": "PP3", "rule": {"genomic.conservation": "conserved"}},
    { "code": "PP5", "rule": {"external.HGMD.tag": "DM"}},
    { "code": "PP5", "rule": {"external.CLINVAR": {"$in": ["CLNSIG=5", "CLNSIG=4"]}}},
    { "code": "PP5", "rule": {"external.[LOVD]": {"$in": ["Path: +/?", "Path: +/+"]}}},
    { "code": "PPX1", "rule": {"frequencies.ExAC_1000G_ESP6500": "null_freq"}},
    { "code": "PPX1", "rule": {"$$aggregate": {"$all": ["REQ_rare", "REQ_GP_inh_ar"]}}},
    { "code": "PPX2", "rule": {"$$aggregate": {"$all": ["REQ_overlap_pat", "REQ_novel_aa", "REQ_aa_diff"]}}},
    ### BP*
    { "code": "BP1", "rule": {"$$aggregate": {"$all": ["REQ_missense", "REQ_GP_lof_only"]}}},
    { "code": "BP2", "rule": {"family.phase": "in_cis_pathogenic"}},
    { "code": "BP2", "rule": {"$$aggregate": {"$all": ["REQ_in_trans_pathogenic", "REQ_GP_inh_ad"]}}},
    { "code": "BP3", "rule": {"$$aggregate": {"$all": ["REQ_inframe", "REQ_repeat"]}}},
    { "code": "BP4", "rule": {"refassessment.*.ref_prediction": "neu"}},
    { "code": "BP4", "rule": {"transcript.SIFT": "tolerated"}},
    { "code": "BP4", "rule": {"transcript.PP2": "benign"}},
    { "code": "BP4", "rule": {"transcript.splice_Effect": "no_effect"}},
    { "code": "BP4", "rule": {"genomic.conservation": "non-conserved"}},
    { "code": "BP6", "rule": {"external.CLINVAR": {"$in": ["CLNSIG=2", "CLNSIG=3"]}}},
    { "code": "BP6", "rule": {"external.[LOVD]": {"$in": ["Path: -/?", "Path: -/-"]}}},
    { "code": "BP7", "rule": {"$$aggregate": {"$all": ["REQ_no_aa_change", "REQ_non-conserved", "REQ_no_splice_effect"]}}},
    { "code": "BPX1", "rule": {"refassessment.*.ref_prot": "prot-"}},
    { "code": "BPX1", "rule": {"refassessment.*.ref_rna": "rna-"}},
    { "code": "BPX1", "rule": {"refassessment.*.ref_msi": "msi-"}},
    { "code": "BPX2", "rule": {"$$aggregate": {"$all": ["REQ_overlap_ben", "REQ_same_aa"]}}},
    ### BS*
    { "code": "BS1", "rule": {"frequencies.inDB": {"$all": ["≥lo_freq_cutoff", "<hi_freq_cutoff"]}}},
    { "code": "BS1", "rule": {"frequencies.ExAC_1000G_ESP6500": {"$all": ["≥lo_freq_cutoff", "<hi_freq_cutoff"]}}},
    { "code": "BS2", "rule": {"refassessment.*.ref_population": "in_healthy"}},
    { "code": "BS3", "rule": {"refassessment.*.ref_prot": "prot--"}},
    { "code": "BS3", "rule": {"refassessment.*.ref_rna": "rna--"}},
    { "code": "BS3", "rule": {"refassessment.*.ref_msi": "msi--"}},
    { "code": "BS3", "rule": {"refassessment.*.ref_ihc": "mmr_noloss"}},
    { "code": "BS4", "rule": {"refassessment.*.ref_segregation": "segr-"}},
    { "code": "BS4", "rule": {"family.segregation": "segr-"}},
    { "code": "BSX1", "rule": {"external.InSight": {"$in": ["Path: -/?", "Path: -/-"]}}},
    ### BA*
    { "code": "BA1", "rule": {"frequencies.inDB": "≥hi_freq_cutoff"}},
    { "code": "BA1", "rule": {"frequencies.ExAC_1000G_ESP6500": "≥hi_freq_cutoff"}},
    { "code": "BAX1", "rule": {"external.BIC.Clinically_Important": "no"}}

#    {
#        "code": "XXX",
#        "rule": {"$$aggregate": {"$atleast": [1, "REQ-1", "REQ-2", "REQ-3"]}}
#    },

]
