"""Add JSON schema table

Revision ID: 022118518e99
Revises: 4fef0af39a20
Create Date: 2019-02-28 07:25:25.613054

"""

# revision identifiers, used by Alembic.
revision = "022118518e99"
down_revision = "4fef0af39a20"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jsonschema",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jsonschema")),
    )

    op.create_index("ix_jsonschema_unique", "jsonschema", ["name", "version"], unique=True)

    op.add_column(
        "annotation",
        sa.Column("schema_version", sa.Integer(), server_default=sa.FetchedValue(), nullable=False),
    )
    op.add_column(
        "filterconfig",
        sa.Column("schema_version", sa.Integer(), server_default=sa.FetchedValue(), nullable=False),
    )

    print("!!! Remember to run update on JSON schema table !!!")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filterconfig", "schema_version")
    op.drop_column("annotation", "schema_version")
    op.drop_table("jsonschema")
    # ### end Alembic commands ###
