"""Migrate interpretation state

Revision ID: 24e583974569
Revises: 1675e8d8b078
Create Date: 2021-12-13 09:38:47.610311

"""

# revision identifiers, used by Alembic.
revision = "24e583974569"
down_revision = "1675e8d8b078"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.dialects.postgresql import JSONB
from vardb.util.mutjson import JSONMutableDict


def upgrade():
    # Update manuallyIncludedAlleles from an array to an object:
    # From: {"manuallyAddedAlleles": [1,2,3]}
    # To: {"manuallyAddedAlleles": {"cnv": [], "snv": [1,2,3]}}

    conn = op.get_bind()
    # Analysis allele states:
    for tbl in ["analysisinterpretation", "alleleinterpretation", "interpretationstatehistory"]:
        conn.execute(
            """
            UPDATE {} 
            SET state=jsonb_set(
                state, 
                '{{manuallyAddedAlleles}}', 
                ('{{"cnv": [], "snv": '::text || (state->'manuallyAddedAlleles')::text || '}}'::text)::jsonb
            ) WHERE 
                state->'manuallyAddedAlleles' is not null
            """.format(
                tbl
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
