"""cleanup customannotation

Revision ID: 4046ee04dd46
Revises: d394766ada41
Create Date: 2021-08-26 11:59:02.611145

"""

# revision identifiers, used by Alembic.
revision = "4046ee04dd46"
down_revision = "d394766ada41"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


from sqlalchemy.sql import table, column

# from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm.session import Session
from api.config import config
from vardb.datamodel.jsonschemas.update_schemas import update_schemas
from vardb.datamodel.annotationshadow import create_trigger_sql
from api.config.customannotationconfig import customannotationconfig

customAnnotationTbl = table(
    "customannotation", column("id", sa.Integer), column("annotations", JSONB)
)


def upgrade():
    conn = op.get_bind()
    session = Session(bind=conn)

    annotations = conn.execution_options(stream_results=True).execute(
        sa.select([customAnnotationTbl.c.id, customAnnotationTbl.c.annotations])
    )
    for a in annotations:
        # look over keys of a
        for a_grp_k in a.annotations.keys():
            # check if key exsits in customannotationconfig
            if a_grp_k not in customannotationconfig.keys():
                # TODO: how to handle this?
                continue
            # use only sub_keys that are found as sub_keys in customannotationconfig
            valid_keys = [e["key"] for e in customannotationconfig[a_grp_k]]
            a.annotations[a_grp_k] = {
                k: v for k, v in a.annotations[a_grp_k].items() if k in valid_keys
            }
        conn.execute(
            sa.update(customAnnotationTbl)
            .where(customAnnotationTbl.c.id == a.id)
            .values({"annotations": a.annotations})
        )
    conn.execute(create_trigger_sql(config))
    update_schemas(session)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
