"""add-e-mail-to-user

Revision ID: 4629b478b291
Revises: d099628590c9
Create Date: 2018-10-25 10:52:14.229198

"""

# revision identifiers, used by Alembic.
revision = "4629b478b291"
down_revision = "d099628590c9"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u"user", sa.Column("email", sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u"user", "email")
    ### end Alembic commands ###
