"""Allow non-coding transcripts

Revision ID: 4c2844fef850
Revises: 92066141f180
Create Date: 2023-03-29 06:19:26.616930

"""

# revision identifiers, used by Alembic.
revision = "4c2844fef850"
down_revision = "92066141f180"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - looks good ###
    op.alter_column("transcript", "cds_end", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("transcript", "cds_start", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - looks good ###
    op.alter_column("transcript", "cds_start", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("transcript", "cds_end", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
