"""Revert transcripts from -1-index to 0-indexed

Revision ID: 7fddcdb9e856
Revises: bbe1686834a4
Create Date: 2018-10-17 10:24:19.448276

"""

# revision identifiers, used by Alembic.
revision = "7fddcdb9e856"
down_revision = "bbe1686834a4"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.dialects import postgresql

Transcript = table(
    "transcript",
    column("id", sa.Integer()),
    column("tx_start", sa.Integer()),
    column("tx_end", sa.Integer()),
    column("cds_start", sa.Integer()),
    column("cds_end", sa.Integer()),
    column("exon_starts", postgresql.ARRAY(sa.Integer())),
    column("exon_ends", postgresql.ARRAY(sa.Integer())),
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    transcripts = conn.execute(sa.select(Transcript.c))

    for t in transcripts:
        values = dict()
        for v in ["tx_start", "tx_end", "cds_start", "cds_end"]:
            values[v] = getattr(t, v) + 1
        values["exon_starts"] = [es + 1 for es in t.exon_starts]
        values["exon_ends"] = [es + 1 for es in t.exon_ends]

        conn.execute(sa.update(Transcript).where(Transcript.c.id == t.id).values(**values))

    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("Downgrade not possible")
