"""Update gene panel format

Revision ID: fd1939667656
Revises: 4046ee04dd46
Create Date: 2021-10-06 13:55:55.079459

"""

# revision identifiers, used by Alembic.
revision = "fd1939667656"
down_revision = "4046ee04dd46"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic, adjusted by FB [stackoverflow.com/questions/22599391] ###
    op.alter_column("transcript", "transcript_name", nullable=False, new_column_name="name")
    op.add_column("transcript", sa.Column("inheritance", sa.String(), nullable=True))
    op.add_column("transcript", sa.Column("source", sa.String(), nullable=True))
    op.create_unique_constraint(op.f("uq_transcript_name"), "transcript", ["name"])
    op.drop_constraint("uq_transcript_transcript_name", "transcript", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted by FB [stackoverflow.com/questions/22599391] ###
    op.alter_column("transcript", "name", nullable=False, new_column_name="transcript_name")
    op.create_unique_constraint("uq_transcript_transcript_name", "transcript", ["transcript_name"])
    op.drop_constraint(op.f("uq_transcript_name"), "transcript", type_="unique")
    op.drop_column("transcript", "source")
    op.drop_column("transcript", "inheritance")
    # ### end Alembic commands ###
