#!/bin/bash -e

curdir() {
    cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}

clone() {
    git clone --depth=1 "$1" "$2"
}

ELLA_URL=https://gitlab.com/alleles/ella.git
TESTDATA_URL=https://gitlab.com/alleles/ella-testdata.git
ELLA_REPO=$(curdir)/ella
TESTDATA_REPO=${ELLA_REPO}/ella-testdata

if [[ ! -d "$(curdir)/ella" ]]; then
    clone "$ELLA_URL" "$ELLA_REPO"
fi
pushd "${ELLA_REPO}"

if [[ ! -d "${TESTDATA_REPO}" ]]; then
    clone "${TESTDATA_URL}" "${TESTDATA_REPO}"
fi

### Autogenerated follows ###
