# -*- coding: utf-8 -*-

customannotationconfig = {
    "external": [
        {
            "key": "LOVD_genomed_China-APC",
            "name": "LOVD genomed China",
            "only_for_genes": [583],
            "url_for_genes": {
                "583": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=APC"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-APC",
            "name": "LOVD - Shared APC",
            "only_for_genes": [583],
            "url_for_genes": {"583": "https://databases.lovd.nl/shared/view/APC"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_InSiGHT-APC",
            "name": "LOVD InSiGHT (not in use)",
            "only_for_genes": [583],
            "url_for_genes": {"583": "https://insight-database.org/genes/APC"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD-APC",
            "name": "UMD",
            "only_for_genes": [583],
            "url_for_genes": {"583": "http://www.umd.be/APC/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-BMPR1A",
            "name": "LOVD - Shared BMPR1A",
            "only_for_genes": [1076],
            "url_for_genes": {"1076": "https://databases.lovd.nl/shared/view/BMPR1A"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "BRCA_Exchange-BRCA1",
            "name": "BRCA Exchange",
            "only_for_genes": [1100],
            "url_for_genes": {"1100": "https://brcaexchange.org/variants?search=BRCA1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "BIC-BRCA1",
            "name": "BIC",
            "only_for_genes": [1100],
            "url_for_genes": {"1100": "http://www.research.nhgri.nih.gov/projects/bic/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-BRCA1",
            "name": "LOVD genomed China",
            "only_for_genes": [1100],
            "url_for_genes": {
                "1100": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=BRCA1"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_IARC_HCI-BRCA1",
            "name": "LOVD IARC HCI",
            "only_for_genes": [1100],
            "url_for_genes": {"1100": "http://hci-exlovd.hci.utah.edu/home.php?select_db=BRCA1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-BRCA1",
            "name": "LOVD - Shared BRCA1",
            "only_for_genes": [1100],
            "url_for_genes": {"1100": "https://databases.lovd.nl/shared/view/BRCA1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD_BRCAshare-BRCA1",
            "name": "UMD BRCAshare",
            "only_for_genes": [1100],
            "url_for_genes": {"1100": "http://www.umd.be/BRCA1/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "BRCA_Exchange-BRCA2",
            "name": "BRCA Exchange",
            "only_for_genes": [1101],
            "url_for_genes": {"1101": "https://brcaexchange.org/variants?search=BRCA2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "BIC-BRCA2",
            "name": "BIC",
            "only_for_genes": [1101],
            "url_for_genes": {"1101": "http://www.research.nhgri.nih.gov/projects/bic/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-BRCA2",
            "name": "LOVD genomed China",
            "only_for_genes": [1101],
            "url_for_genes": {
                "1101": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=BRCA2"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_IARC_HCI-BRCA2",
            "name": "LOVD IARC HCI",
            "only_for_genes": [1101],
            "url_for_genes": {"1101": "http://hci-exlovd.hci.utah.edu/home.php?select_db=BRCA2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-BRCA2",
            "name": "LOVD - Shared BRCA2",
            "only_for_genes": [1101],
            "url_for_genes": {"1101": "https://databases.lovd.nl/shared/view/BRCA2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD_BRCAshare-BRCA2",
            "name": "UMD BRCAshare",
            "only_for_genes": [1101],
            "url_for_genes": {"1101": "http://www.umd.be/BRCA2/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-CDH1",
            "name": "LOVD genomed China",
            "only_for_genes": [1748],
            "url_for_genes": {
                "1748": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=CDH1"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-CDH1",
            "name": "LOVD - Shared CDH1",
            "only_for_genes": [1748],
            "url_for_genes": {"1748": "https://databases.lovd.nl/shared/view/CDH1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-CDKN2A",
            "name": "LOVD - Shared CDKN2A",
            "only_for_genes": [1787],
            "url_for_genes": {"1787": "https://databases.lovd.nl/shared/view/CDKN2A"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD-DICER1",
            "name": "LOVD",
            "only_for_genes": [17098],
            "url_for_genes": {
                "17098": "https://grenada.lumc.nl/LOVD2/mendelian_genes/home.php?select_db=DICER1"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-DICER1",
            "name": "LOVD - Shared DICER1",
            "only_for_genes": [17098],
            "url_for_genes": {"17098": "https://databases.lovd.nl/shared/genes/DICER1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_medgen-EXT1",
            "name": "LOVD medgen (not in use)",
            "only_for_genes": [3512],
            "url_for_genes": {"3512": "http://medgen.ua.ac.be/LOVDv.2.0/home.php?select_db=EXT1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-EXT1",
            "name": "LOVD - Shared EXT1",
            "only_for_genes": [3512],
            "url_for_genes": {"3512": "https://databases.lovd.nl/shared/view/EXT1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_medgen-EXT2",
            "name": "LOVD medgen (not in use)",
            "only_for_genes": [3513],
            "url_for_genes": {"3513": "http://medgen.ua.ac.be/LOVDv.2.0/home.php?select_db=EXT2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-EXT2",
            "name": "LOVD - Shared EXT2",
            "only_for_genes": [3513],
            "url_for_genes": {"3513": "https://databases.lovd.nl/shared/view/EXT2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-FLCN ",
            "name": "LOVD - Shared FLCN",
            "only_for_genes": [27310],
            "url_for_genes": {"27310": "https://databases.lovd.nl/shared/view/FLCN"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-HOXB13",
            "name": "LOVD - Shared HOXB13",
            "only_for_genes": [5112],
            "url_for_genes": {"5112": "https://databases.lovd.nl/shared/genes/HOXB13"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-MLH1",
            "name": "LOVD genomed China",
            "only_for_genes": [7127],
            "url_for_genes": {
                "7127": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=MLH1"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_hci_priors-MLH1",
            "name": "LOVD hci priors",
            "only_for_genes": [7127],
            "url_for_genes": {"7127": "http://hci-lovd.hci.utah.edu/home.php?select_db=MLH1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_InSiGHT-MLH1",
            "name": "LOVD InSiGHT (not in use)",
            "only_for_genes": [7127],
            "url_for_genes": {"7127": "https://insight-database.org/genes/MLH1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-MLH1",
            "name": "LOVD - Shared MLH1",
            "only_for_genes": [7127],
            "url_for_genes": {"7127": "https://databases.lovd.nl/shared/view/MLH1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD-MLH1",
            "name": "UMD",
            "only_for_genes": [7127],
            "url_for_genes": {"7127": "http://www.umd.be/MLH1/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-MSH2",
            "name": "LOVD genomed China",
            "only_for_genes": [7325],
            "url_for_genes": {
                "7325": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=MSH2"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_hci_priors-MSH2",
            "name": "LOVD hci priors",
            "only_for_genes": [7325],
            "url_for_genes": {"7325": "http://hci-lovd.hci.utah.edu/home.php?select_db=MSH2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_InSiGHT-MSH2",
            "name": "LOVD InSiGHT (not in use)",
            "only_for_genes": [7325],
            "url_for_genes": {"7325": "https://insight-database.org/genes/MSH2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-MSH2",
            "name": "LOVD - Shared MSH2",
            "only_for_genes": [7325],
            "url_for_genes": {"7325": "https://databases.lovd.nl/shared/view/MSH2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD-MSH2",
            "name": "UMD",
            "only_for_genes": [7325],
            "url_for_genes": {"7325": "http://www.umd.be/MSH2/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-MSH6",
            "name": "LOVD genomed China",
            "only_for_genes": [7329],
            "url_for_genes": {
                "7329": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=MSH6"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_hci_priors-MSH6",
            "name": "LOVD hci priors",
            "only_for_genes": [7329],
            "url_for_genes": {"7329": "http://hci-lovd.hci.utah.edu/home.php?select_db=MSH6"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_InSiGHT-MSH6",
            "name": "LOVD InSiGHT (not in use)",
            "only_for_genes": [7329],
            "url_for_genes": {"7329": "https://insight-database.org/genes/MSH6"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-MSH6",
            "name": "LOVD - Shared MSH6",
            "only_for_genes": [7329],
            "url_for_genes": {"7329": "https://databases.lovd.nl/shared/view/MSH6"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD-MSH6",
            "name": "UMD",
            "only_for_genes": [7329],
            "url_for_genes": {"7329": "http://www.umd.be/MSH6/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_InSiGHT-MUTYH",
            "name": "LOVD InSiGHT (not in use)",
            "only_for_genes": [7527],
            "url_for_genes": {"7527": "https://insight-database.org/genes/MUTYH"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-MUTYH",
            "name": "LOVD - Shared MUTYH",
            "only_for_genes": [7527],
            "url_for_genes": {"7527": "https://databases.lovd.nl/shared/view/MUTYH"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD-MUTYH",
            "name": "UMD",
            "only_for_genes": [7527],
            "url_for_genes": {"7527": "http://www.umd.be/MUTYH/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-PALB2",
            "name": "LOVD genomed China",
            "only_for_genes": [26144],
            "url_for_genes": {
                "26144": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=PALB2"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-PALB2",
            "name": "LOVD - Shared PALB2",
            "only_for_genes": [26144],
            "url_for_genes": {"26144": "https://databases.lovd.nl/shared/view/PALB2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_hci_priors-PMS2",
            "name": "LOVD hci priors",
            "only_for_genes": [9122],
            "url_for_genes": {"9122": "http://hci-lovd.hci.utah.edu/home.php?select_db=PMS2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_InSiGHT-PMS2",
            "name": "LOVD InSiGHT (not in use)",
            "only_for_genes": [9122],
            "url_for_genes": {"9122": "https://insight-database.org/genes/PMS2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-PMS2",
            "name": "LOVD - Shared PMS2",
            "only_for_genes": [9122],
            "url_for_genes": {"9122": "https://databases.lovd.nl/shared/view/PMS2"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-POLD1",
            "name": "LOVD - Shared POLD1",
            "only_for_genes": [9175],
            "url_for_genes": {"9175": "https://databases.lovd.nl/shared/view/POLD1"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-POLE",
            "name": "LOVD - Shared POLE",
            "only_for_genes": [9177],
            "url_for_genes": {"9177": "https://databases.lovd.nl/shared/view/POLE"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-PTEN",
            "name": "LOVD genomed China",
            "only_for_genes": [9588],
            "url_for_genes": {
                "9588": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=PTEN"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared -PTEN",
            "name": "LOVD - Shared PTEN",
            "only_for_genes": [9588],
            "url_for_genes": {"9588": "https://databases.lovd.nl/shared/view/PTEN"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_whole_genome-PTEN",
            "name": "LOVD whole genome",
            "only_for_genes": [9588],
            "url_for_genes": {"9588": "http://databases.lovd.nl/whole_genome/view/PTEN"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_lohmann-RB1",
            "name": "LOVD lohmann",
            "only_for_genes": [9884],
            "url_for_genes": {
                "9884": "http://rb1-lsdb.d-lohmann.de/variants.php?action=search_unique&select_db=RB1"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-SDHB",
            "name": "LOVD - Shared SDHB",
            "only_for_genes": [10681],
            "url_for_genes": {"10681": "https://databases.lovd.nl/shared/view/SDHB"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-SDHD",
            "name": "LOVD - Shared SDHD",
            "only_for_genes": [10683],
            "url_for_genes": {"10683": "https://databases.lovd.nl/shared/view/SDHD"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "ARUP-SMAD4",
            "name": "ARUP",
            "only_for_genes": [6770],
            "url_for_genes": {"6770": "http://arup.utah.edu/database/SMAD4/SMAD4_display.php"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-SMAD4",
            "name": "LOVD - Shared SMAD4",
            "only_for_genes": [6770],
            "url_for_genes": {"6770": "https://databases.lovd.nl/shared/view/SMAD4"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-STK11",
            "name": "LOVD genomed China",
            "only_for_genes": [11389],
            "url_for_genes": {
                "11389": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=STK11"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-STK11",
            "name": "LOVD - Shared STK11",
            "only_for_genes": [11389],
            "url_for_genes": {"11389": "https://databases.lovd.nl/shared/view/STK11"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "IARC-TP53",
            "name": "IARC",
            "only_for_genes": [11998],
            "url_for_genes": {"11998": "http://p53.iarc.fr/TP53GeneVariations.aspx"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_shared-TP53",
            "name": "LOVD - Shared TP53",
            "only_for_genes": [11998],
            "url_for_genes": {"11998": "https://databases.lovd.nl/shared/view/TP53"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "LOVD_genomed_China-VHL",
            "name": "LOVD genomed China",
            "only_for_genes": [12687],
            "url_for_genes": {
                "12687": "http://www.genomed.org/lovd2/variants.php?action=search_unique&select_db=VHL"
            },
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "UMD-VHL",
            "name": "UMD",
            "only_for_genes": [12687],
            "url_for_genes": {"12687": "http://www.umd.be/VHL/"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "VHLdb-VHL",
            "name": "VHLdb",
            "only_for_genes": [12687],
            "url_for_genes": {"12687": "http://vhldb.bio.unipd.it/mutations"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {
            "key": "TP53-web-site",
            "name": "The TP53 Web Site",
            "only_for_genes": [11998],
            "url_for_genes": {"11998": "http://p53.fr/download-the-database"},
            "options": [
                ["Pathogenic", "pathogenic"],
                ["Likely pathogenic", "likely_pathogenic"],
                ["Uncertain significance", "uncertain_significance"],
                ["Likely benign", "likely_benign"],
                ["Benign", "benign"],
                ["Conflicting", "conflicting"],
                ["Indirectly relevant", "indirectly_relevant"],
                ["Nothing found", "none_found"],
                ["Other", "other"],
            ],
        },
        {"key": "other_extdb", "name": "Other", "text": True},
    ],
    "prediction": [
        {
            "key": "ortholog_conservation",
            "name": "Ortholog conservation",
            "options": [["Conserved", "conserved"], ["Non-conserved", "non-conserved"]],
        },
        {
            "key": "paralog_conservation",
            "name": "Paralog conservation",
            "options": [["Conserved", "conserved"], ["Non-conserved", "non-conserved"]],
        },
        {
            "key": "dna_conservation",
            "name": "DNA conservation",
            "options": [["Conserved", "conserved"], ["Non-conserved", "non-conserved"]],
        },
        {
            "key": "domain",
            "name": "Domain",
            "options": [
                ["Critical functional domain", "critical_domain"],
                ["Critical functional amino acid", "critical_site"],
            ],
        },
        {
            "key": "repeat",
            "name": "Repeat",
            "options": [["Repeat region", "repeat"], ["Non-repeat region", "non_repeat"]],
        },
        {
            "key": "splice_Effect_manual",
            "name": "Splice site effect",
            "options": [
                ["Splice site lost", "predicted_lost"],
                ["De novo splice site", "de_novo"],
                ["No splice site effect", "no_effect"],
            ],
        },
    ],
}
